logging:
  level:
    root: INFO
    org.springframefork.web: DEBUG
    springfox.documentation: INFO
  file:
    name: log/application.log

spring:
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    generate-ddl: false

  datasource:
    initialization-mode: never
    url: jdbc:postgresql://localhost:5432/pet_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  banner:
    location: classpath:/static/banner.txt

  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      cookie:
        http-only: true
      tracking-modes: cookie

springfox:
  documentation:
    swagger-ui:
      base-url: /documentation
    swagger:
      v2:
        use-model-v3: true

pet-project:
  autologin: true
  min-username-length: 1
  min-password-length: 1
  client-url: http://localhost:5000

jwt:
  secret: sdfivisv3iufhviuvhu8hfgisuhga