logging:
  level:
    org.springframefork: INFO
    springfox.documentation: INFO
  file:
    name: log/application.log

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

  datasource:
    initialization-mode: never
    url: jdbc:postgresql://localhost:5432/pet_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  banner:
    location: classpath:/static/banner.txt

  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl

server:
  error:
    whitelabel:
      enabled: false

springfox:
  documentation:
    swagger-ui:
      base-url: /documentation
    swagger:
      v2:
        use-model-v3: true

pet-project:
  autologin: true
  min-username-length: 1
  min-password-length: 1
  client-url: http://localhost:5000

jwt:
  secret: sdfivisv3iufhviuvhu8hfgisuhga